// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCraG63pDXWY0gSO-XyPFPuCauA2TNUGVw',
    appId: '1:476023449255:web:9d976d9e3ecfbadb401d82',
    messagingSenderId: '476023449255',
    projectId: 'smart-mat-abc-app',
    authDomain: 'smart-mat-abc-app.firebaseapp.com',
    storageBucket: 'smart-mat-abc-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFPAOb10vuhz2HxduCx-an2QY9S-m5GM',
    appId: '1:476023449255:android:57f5e1edcf12371a401d82',
    messagingSenderId: '476023449255',
    projectId: 'smart-mat-abc-app',
    storageBucket: 'smart-mat-abc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaQYqC8nP2H7V-urzQqmjA9kfgsMq43Hg',
    appId: '1:476023449255:ios:581b8b7179535181401d82',
    messagingSenderId: '476023449255',
    projectId: 'smart-mat-abc-app',
    storageBucket: 'smart-mat-abc-app.firebasestorage.app',
    iosBundleId: 'com.example.smartmatabcapp',
  );

}